import { useEffect, useState } from "react";
import { Eye } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

// Page-view counter. Best-effort: silently no-ops if the `page_views`
// table doesn't exist yet (the Supabase project is empty so far).
// Schema (run in Supabase SQL editor when ready):
//
//   create table public.page_views (
//     id bigint generated by default as identity primary key,
//     path text not null default '/',
//     created_at timestamptz not null default now()
//   );
//   alter table public.page_views enable row level security;
//   create policy "anyone can insert" on public.page_views for insert with check (true);
//   create policy "anyone can read count" on public.page_views for select using (true);
export function ViewCounter() {
  const [count, setCount] = useState<number | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function track() {
      try {
        await supabase.from("page_views").insert({ path: window.location.pathname });
        const { count } = await supabase
          .from("page_views")
          .select("*", { count: "exact", head: true });
        if (!cancelled) setCount(count ?? 0);
      } catch {
        // Table not provisioned yet — that's fine, we just don't show a count.
      }
    }

    track();
    return () => {
      cancelled = true;
    };
  }, []);

  if (count === null) return null;

  return (
    <span className="inline-flex items-center gap-1.5 text-xs text-muted-foreground">
      <Eye className="w-3 h-3" />
      {count.toLocaleString()} views
    </span>
  );
}
